package com.example.ui

import android.content.Context
import android.content.Intent
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import androidx.core.content.FileProvider
import com.example.data.Transaction
import java.io.File
import java.io.FileOutputStream
import java.text.NumberFormat
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object PdfUtils {

    private val timestampFormat = SimpleDateFormat("dd MMM yyyy, hh:mm a", Locale.getDefault())
    private val dateOnlyFormat = SimpleDateFormat("dd MMM yyyy", Locale.getDefault())

    private fun truncateText(text: String, maxWidth: Float, paint: Paint): String {
        if (paint.measureText(text) <= maxWidth) return text
        var truncated = text
        while (truncated.isNotEmpty() && paint.measureText("$truncated...") > maxWidth) {
            truncated = truncated.dropLast(1)
        }
        return if (truncated.isEmpty()) "..." else "$truncated..."
    }

    // ── Color palette ──────────────────────────────────────────
    private val NAVY       = Color.parseColor("#0F172A")
    private val DARK_SLATE = Color.parseColor("#1E293B")
    private val SLATE      = Color.parseColor("#334155")
    private val GRAY       = Color.parseColor("#64748B")
    private val LIGHT_GRAY = Color.parseColor("#94A3B8")
    private val BORDER     = Color.parseColor("#CBD5E1")
    private val BG_LIGHT   = Color.parseColor("#F1F5F9")
    private val BG_PAGE    = Color.parseColor("#F8FAFC")
    private val GREEN_DARK = Color.parseColor("#15803D")
    private val GREEN_LITE = Color.parseColor("#DCFCE7")
    private val GREEN_MID  = Color.parseColor("#22C55E")
    private val RED_DARK   = Color.parseColor("#B91C1C")
    private val RED_LITE   = Color.parseColor("#FEE2E2")
    private val PURPLE     = Color.parseColor("#5D53EA")
    private val PURPLE_LT  = Color.parseColor("#EEF2FF")

    // ═══════════════════════════════════════════════════════════
    //  1. SINGLE RECEIPT PDF  (A5 — 420 × 595)
    // ═══════════════════════════════════════════════════════════
    fun drawCommonHeader(
        c: Canvas,
        p: Paint,
        pw: Int,
        margin: Float,
        reportTitle: String,
        generatedBy: String,
        dateRange: String,
        projectName: String,
        siteAddress: String,
        yStart: Float
    ): Float {
        var y = yStart

        // 1. Company Logo / Info (Left-aligned)
        p.color = Color.parseColor("#0F172A") // Navy/Charcoal
        p.textSize = 10f
        p.isFakeBoldText = true
        p.textAlign = Paint.Align.LEFT
        c.drawText("Company", margin, y, p)
        
        p.isFakeBoldText = false
        p.color = Color.parseColor("#64748B") // Slate gray
        p.textSize = 9f
        c.drawText("Pune", margin, y + 12f, p)
        c.drawText("GST : N/A", margin, y + 24f, p)

        // 2. Report Title & Info (Right-aligned)
        p.color = Color.parseColor("#0F172A")
        p.textSize = 14f
        p.isFakeBoldText = true
        p.textAlign = Paint.Align.RIGHT
        c.drawText(reportTitle, pw - margin, y, p)

        p.isFakeBoldText = false
        p.color = Color.parseColor("#64748B")
        p.textSize = 9f
        c.drawText("Generated By: $generatedBy", pw - margin, y + 12f, p)
        c.drawText("Date Range: $dateRange", pw - margin, y + 24f, p)

        y += 36f

        // 3. Divider Line
        p.color = Color.parseColor("#CBD5E1") // light grey divider
        p.strokeWidth = 1f
        c.drawLine(margin, y, pw - margin, y, p)

        y += 15f

        // 4. Project Card Box (light grey background rounded box)
        val boxHeight = 45f
        p.color = Color.parseColor("#F1F5F9") // Light grey box fill
        p.style = Paint.Style.FILL
        c.drawRoundRect(margin, y, pw - margin, y + boxHeight, 6f, 6f, p)

        // Project Info Text inside Card
        p.color = Color.parseColor("#1E293B")
        p.textSize = 10f
        p.textAlign = Paint.Align.LEFT
        p.isFakeBoldText = true
        c.drawText("Project: ", margin + 12f, y + 18f, p)
        val projWidth = p.measureText("Project: ")
        p.isFakeBoldText = false
        p.color = Color.parseColor("#0F172A")
        c.drawText(projectName, margin + 12f + projWidth, y + 18f, p)

        p.color = Color.parseColor("#1E293B")
        p.isFakeBoldText = true
        c.drawText("Site Address: ", margin + 12f, y + 32f, p)
        val siteWidth = p.measureText("Site Address: ")
        p.isFakeBoldText = false
        p.color = Color.parseColor("#0F172A")
        c.drawText(siteAddress.replace("\n", " "), margin + 12f + siteWidth, y + 32f, p)

        y += boxHeight + 15f
        return y
    }

    fun generateReceiptPdfFile(
        context: Context,
        txId: Int,
        name: String,
        amount: String,
        date: String,
        paymentMethod: String = "Cash",
        remark: String = "",
        isMoneyIn: Boolean = false,
        projectName: String = "Treasure garden"
    ): File {
        val fileName = "Receipt_${txId}_${System.currentTimeMillis()}.pdf"
        val file = File(context.cacheDir, fileName)
        val doc = PdfDocument()

        val pw = 420; val ph = 595
        val page = doc.startPage(PdfDocument.PageInfo.Builder(pw, ph, 1).create())
        val c = page.canvas
        val p = Paint().apply { isAntiAlias = true }

        // page background
        p.color = BG_PAGE; c.drawRect(0f, 0f, pw.toFloat(), ph.toFloat(), p)

        val margin = 30f
        var y = 40f

        // 1. Header (Left-aligned company info, Right-aligned Receipt title)
        p.color = Color.parseColor("#0F172A")
        p.textSize = 10f; p.isFakeBoldText = true; p.textAlign = Paint.Align.LEFT
        c.drawText("Company", margin, y, p)
        p.isFakeBoldText = false; p.color = Color.parseColor("#64748B")
        c.drawText("Pune", margin, y + 12f, p)
        c.drawText("Pune", margin, y + 24f, p)
        c.drawText("GST : N/A", margin, y + 36f, p)

        p.color = Color.parseColor("#0F172A")
        p.textSize = 14f; p.isFakeBoldText = true; p.textAlign = Paint.Align.RIGHT
        val docTitle = if (isMoneyIn) "Payment Received" else "Payment Paid"
        c.drawText(docTitle, pw - margin, y, p)
        p.isFakeBoldText = false; p.color = Color.parseColor("#64748B")
        p.textSize = 9f
        c.drawText("Payment Date:", pw - margin - 70f, y + 16f, p)
        p.color = Color.parseColor("#0F172A"); p.isFakeBoldText = true
        c.drawText(date, pw - margin, y + 16f, p)

        y += 48f

        // Divider line
        p.color = Color.parseColor("#CBD5E1"); p.strokeWidth = 0.5f
        c.drawLine(margin, y, pw - margin, y, p)

        y += 20f

        // Project Info
        p.color = Color.parseColor("#64748B"); p.textSize = 9f; p.textAlign = Paint.Align.LEFT; p.isFakeBoldText = false
        c.drawText("Project:", margin, y, p)
        p.color = Color.parseColor("#0F172A"); p.textSize = 10f; p.isFakeBoldText = true
        c.drawText(projectName, margin, y + 14f, p)

        y += 34f

        // To Info
        p.color = Color.parseColor("#64748B"); p.textSize = 9f; p.isFakeBoldText = false
        c.drawText("To:", margin, y, p)
        p.color = Color.parseColor("#0F172A"); p.textSize = 10f; p.isFakeBoldText = true
        c.drawText(name, margin, y + 14f, p)
        p.color = Color.parseColor("#64748B"); p.textSize = 8f; p.isFakeBoldText = false
        c.drawText("GST: NA", margin, y + 26f, p)

        y += 46f

        // Subject Info
        p.color = Color.parseColor("#64748B"); p.textSize = 9f
        c.drawText("Subject:", margin, y, p)
        p.color = Color.parseColor("#0F172A"); p.textSize = 10f; p.isFakeBoldText = true
        val subjectText = if (isMoneyIn) "Payment Received" else "Payment Paid"
        c.drawText(subjectText, margin, y + 14f, p)

        y += 34f

        // Body Text
        p.color = Color.parseColor("#0F172A"); p.textSize = 9f; p.isFakeBoldText = false
        c.drawText("Dear Sir/Madam,", margin, y, p)
        val actionWord = if (isMoneyIn) "received" else "paid"
        c.drawText("We confirm payment was $actionWord on $date.", margin, y + 14f, p)

        y += 28f

        // Table
        val col1X = margin
        val col2X = margin + 110f
        val tableW = pw - 2 * margin
        val rowH = 22f

        fun drawTableRow(label: String, valText: String, isBoldVal: Boolean, yPos: Float) {
            // Draw outer border and dividers
            p.color = Color.parseColor("#CBD5E1"); p.style = Paint.Style.STROKE; p.strokeWidth = 0.5f
            c.drawRect(col1X, yPos, col1X + tableW, yPos + rowH, p)
            c.drawLine(col2X, yPos, col2X, yPos + rowH, p)
            
            p.style = Paint.Style.FILL
            p.color = Color.parseColor("#475569"); p.textSize = 9f; p.textAlign = Paint.Align.LEFT
            c.drawText(label, col1X + 8f, yPos + 14f, p)
            
            p.color = if (isBoldVal && label == "Amount") (if (isMoneyIn) GREEN_DARK else RED_DARK) else Color.parseColor("#0F172A")
            p.isFakeBoldText = isBoldVal
            if (label == "Amount") {
                p.textAlign = Paint.Align.RIGHT
                c.drawText(valText, col1X + tableW - 8f, yPos + 14f, p)
            } else {
                p.textAlign = Paint.Align.LEFT
                c.drawText(valText, col2X + 8f, yPos + 14f, p)
            }
            p.isFakeBoldText = false
        }

        drawTableRow("Amount", amount, true, y); y += rowH
        drawTableRow("Payment Date", date, false, y); y += rowH
        drawTableRow("Payment Method", paymentMethod, false, y); y += rowH
        drawTableRow("Remark", remark, false, y); y += rowH
        drawTableRow("Attachment", "", false, y); y += rowH

        y += 25f

        // Bottom Message
        p.color = Color.parseColor("#64748B"); p.textSize = 8f; p.textAlign = Paint.Align.LEFT
        c.drawText("Thank you for your services . Please contact us for any clarifications.", margin, y, p)

        // Signature
        p.color = Color.parseColor("#0F172A"); p.textSize = 9f; p.isFakeBoldText = true; p.textAlign = Paint.Align.RIGHT
        c.drawText("Authorised Signatory", pw - margin, ph - 45f, p)

        doc.finishPage(page)
        FileOutputStream(file).use { doc.writeTo(it) }; doc.close()
        return file
    }

    // ═══════════════════════════════════════════════════════════
    //  2. BALANCE REVIEW / PARTY LEDGER PDF  (A4 — 595 × 842)
    // ═══════════════════════════════════════════════════════════
    fun generateBalanceReviewPdfFile(
        context: Context,
        partyName: String,
        projectName: String,
        balance: String,
        statusText: String,
        received: String,
        paid: String,
        transactions: List<Transaction> = emptyList(),
        siteAddress: String = "Treasure Garden Site, India",
        generatedBy: String = "Tejas Harane",
        dateRange: String = "All Time"
    ): File {
        val fileName = "Balance_${partyName.replace(" ", "_")}_${System.currentTimeMillis()}.pdf"
        val file = File(context.cacheDir, fileName)
        val doc = PdfDocument()

        val pw = 595; val ph = 842
        var pageNum = 0
        val margin = 40f
        val contentW = pw - 2 * margin
        val p = Paint().apply { isAntiAlias = true }

        var page: PdfDocument.Page? = null
        var canvas: Canvas? = null
        var yPos = 0f

        fun newPage(): Canvas {
            page?.let { doc.finishPage(it) }
            pageNum++
            val pi = PdfDocument.PageInfo.Builder(pw, ph, pageNum).create()
            page = doc.startPage(pi)
            canvas = page!!.canvas
            val c = canvas!!

            p.color = BG_PAGE; c.drawRect(0f, 0f, pw.toFloat(), ph.toFloat(), p)

            yPos = drawCommonHeader(
                c = c,
                p = p,
                pw = pw,
                margin = margin,
                reportTitle = "Party Ledger Report",
                generatedBy = generatedBy,
                dateRange = dateRange,
                projectName = projectName,
                siteAddress = siteAddress,
                yStart = 40f
            )
            return c
        }

        fun drawTableHeader(c: Canvas) {
            p.color = DARK_SLATE
            c.drawRoundRect(margin, yPos, pw - margin, yPos + 24f, 4f, 4f, p)

            p.color = Color.WHITE; p.textSize = 10f; p.isFakeBoldText = true
            p.textAlign = Paint.Align.LEFT
            c.drawText("S.No", margin + 10f, yPos + 16f, p)
            c.drawText("Date", margin + 50f, yPos + 16f, p)
            c.drawText("Type", margin + 165f, yPos + 16f, p)
            c.drawText("Method", margin + 260f, yPos + 16f, p)
            p.textAlign = Paint.Align.RIGHT
            c.drawText("Amount (₹)", pw - margin - 10f, yPos + 16f, p)

            yPos += 30f
            p.isFakeBoldText = false
        }

        var c = newPage()

        // Party Info card header
        p.textAlign = Paint.Align.LEFT
        p.color = NAVY; p.textSize = 12f; p.isFakeBoldText = true
        c.drawText("PARTY DETAILS", margin, yPos, p)
        yPos += 14f

        p.color = Color.WHITE; c.drawRoundRect(margin, yPos, pw - margin, yPos + 45f, 6f, 6f, p)
        p.color = BORDER; p.style = Paint.Style.STROKE; p.strokeWidth = 0.5f
        c.drawRoundRect(margin, yPos, pw - margin, yPos + 45f, 6f, 6f, p)
        p.style = Paint.Style.FILL

        p.color = GRAY; p.textSize = 10f; p.isFakeBoldText = false
        c.drawText("Party Name:", margin + 16f, yPos + 26f, p)
        p.color = NAVY; p.textSize = 11f; p.isFakeBoldText = true
        c.drawText(partyName, margin + 90f, yPos + 26f, p)
        p.isFakeBoldText = false
        yPos += 60f

        // Cards layout
        val cardH = 50f; val gap = 12f; val cw = (contentW - 2 * gap) / 3

        // Received Card
        p.color = GREEN_LITE; c.drawRoundRect(margin, yPos, margin + cw, yPos + cardH, 6f, 6f, p)
        p.color = GREEN_DARK; p.textAlign = Paint.Align.CENTER; p.textSize = 9f; p.isFakeBoldText = true
        c.drawText("TOTAL RECEIVED", margin + cw / 2, yPos + 18f, p)
        p.textSize = 14f
        c.drawText(received, margin + cw / 2, yPos + 38f, p)

        // Paid Card
        val c2x = margin + cw + gap
        p.color = RED_LITE; c.drawRoundRect(c2x, yPos, c2x + cw, yPos + cardH, 6f, 6f, p)
        p.color = RED_DARK; p.textSize = 9f
        c.drawText("TOTAL PAID", c2x + cw / 2, yPos + 18f, p)
        p.textSize = 14f
        c.drawText(paid, c2x + cw / 2, yPos + 38f, p)

        // Balance Card
        val c3x = margin + 2 * (cw + gap)
        val isAdv = statusText.contains("Advance", true) || statusText.contains("Paid", true)
        val cleanStatus = if (isAdv) "Paid" else "Received"
        val balBg = if (isAdv) GREEN_LITE else RED_LITE
        val balFg = if (isAdv) GREEN_DARK else RED_DARK
        p.color = balBg; c.drawRoundRect(c3x, yPos, c3x + cw, yPos + cardH, 6f, 6f, p)
        p.color = balFg; p.textSize = 9f
        c.drawText("NET BALANCE", c3x + cw / 2, yPos + 16f, p)
        p.textSize = 13f
        c.drawText(balance, c3x + cw / 2, yPos + 32f, p)
        p.textSize = 8f; p.isFakeBoldText = false
        c.drawText(cleanStatus, c3x + cw / 2, yPos + 44f, p)

        yPos += cardH + 24f

        p.textAlign = Paint.Align.LEFT
        p.color = NAVY; p.textSize = 12f; p.isFakeBoldText = true
        c.drawText("TRANSACTION HISTORY", margin, yPos, p)
        p.color = GRAY; p.textSize = 10f; p.isFakeBoldText = false; p.textAlign = Paint.Align.RIGHT
        c.drawText("${transactions.size} entries", pw - margin, yPos, p)
        yPos += 14f

        drawTableHeader(c)

        if (transactions.isEmpty()) {
            yPos += 20f
            p.textAlign = Paint.Align.CENTER; p.color = LIGHT_GRAY; p.textSize = 11f
            c.drawText("No transactions found in selected period.", pw / 2f, yPos, p)
        } else {
            var runningBalance = 0.0
            for ((idx, tx) in transactions.withIndex()) {
                if (yPos > ph - 80f) {
                    c = newPage()
                    drawTableHeader(c)
                }

                val isIn = tx.type == "Money In"
                runningBalance += if (isIn) tx.amount else -tx.amount

                if (idx % 2 == 0) {
                    p.color = Color.argb(15, 0, 0, 0)
                    c.drawRect(margin, yPos - 4f, pw - margin, yPos + 22f, p)
                }

                p.color = GRAY; p.textSize = 10f; p.textAlign = Paint.Align.LEFT; p.isFakeBoldText = false
                c.drawText("${idx + 1}", margin + 10f, yPos + 12f, p)

                p.color = NAVY
                c.drawText(tx.date, margin + 50f, yPos + 12f, p)

                val typeColor = if (isIn) GREEN_DARK else RED_DARK
                p.color = typeColor
                c.drawCircle(margin + 167f, yPos + 8f, 3f, p)
                p.textSize = 10f
                val typeText = if (isIn) "Received" else "Paid"
                c.drawText(typeText, margin + 178f, yPos + 12f, p)

                p.color = SLATE; p.textSize = 9f
                c.drawText(tx.paymentMethod, margin + 260f, yPos + 12f, p)

                p.textAlign = Paint.Align.RIGHT; p.isFakeBoldText = true; p.textSize = 10f
                p.color = typeColor
                val sign = if (isIn) "+" else "-"
                val indFmtVal = NumberFormat.getNumberInstance(Locale.US).apply {
                    maximumFractionDigits = 2; minimumFractionDigits = 2
                }
                val amtText = sign + indFmtVal.format(tx.amount).replace("₹", "₹ ")
                c.drawText(amtText, pw - margin - 10f, yPos + 12f, p)
                p.isFakeBoldText = false

                p.color = Color.parseColor("#E2E8F0"); p.strokeWidth = 0.5f
                c.drawLine(margin, yPos + 20f, pw - margin, yPos + 20f, p)

                yPos += 24f
            }
        }

        val fc = canvas!!
        p.color = BORDER; p.strokeWidth = 1f
        fc.drawLine(margin, ph - 65f, pw - margin, ph - 65f, p)
        p.color = LIGHT_GRAY; p.textSize = 9f; p.isFakeBoldText = false; p.textAlign = Paint.Align.CENTER
        fc.drawText("Generated by ConstructPro  ·  ${timestampFormat.format(Date())}", pw / 2f, ph - 45f, p)
        fc.drawText("This is a computer-generated document and does not require a physical signature.", pw / 2f, ph - 30f, p)

        doc.finishPage(page!!)
        FileOutputStream(file).use { doc.writeTo(it) }; doc.close()
        return file
    }

    // ═══════════════════════════════════════════════════════════
    //  3. PARTY BALANCE REPORT PDF (A4 — 595 × 842)
    // ═══════════════════════════════════════════════════════════
    fun generatePartyBalanceReportPdfFile(
        context: Context,
        projectName: String,
        siteAddress: String,
        generatedBy: String,
        parties: List<com.example.data.Worker>,
        transactions: List<Transaction>,
        dateRange: String = "From Start - Till Now"
    ): File {
        val fileName = "PartyBalanceReport_${System.currentTimeMillis()}.pdf"
        val file = File(context.cacheDir, fileName)
        val doc = PdfDocument()

        val pw = 595; val ph = 842
        var pageNum = 0
        val margin = 40f
        val p = Paint().apply { isAntiAlias = true }

        val indFmt = NumberFormat.getNumberInstance(Locale.US).apply {
            maximumFractionDigits = 2; minimumFractionDigits = 2
        }

        var page: PdfDocument.Page? = null
        var canvas: Canvas? = null
        var yPos = 0f

        fun newPage(): Canvas {
            page?.let { doc.finishPage(it) }
            pageNum++
            val pi = PdfDocument.PageInfo.Builder(pw, ph, pageNum).create()
            page = doc.startPage(pi)
            canvas = page!!.canvas
            val c = canvas!!

            p.color = BG_PAGE; c.drawRect(0f, 0f, pw.toFloat(), ph.toFloat(), p)

            yPos = drawCommonHeader(
                c = c,
                p = p,
                pw = pw,
                margin = margin,
                reportTitle = "Party Balance Report",
                generatedBy = generatedBy,
                dateRange = dateRange,
                projectName = projectName,
                siteAddress = siteAddress,
                yStart = 40f
            )
            return c
        }

        fun drawTableHeader(c: Canvas) {
            p.color = DARK_SLATE
            c.drawRoundRect(margin, yPos, pw - margin, yPos + 24f, 4f, 4f, p)

            p.color = Color.WHITE; p.textSize = 10f; p.isFakeBoldText = true
            p.textAlign = Paint.Align.LEFT
            c.drawText("Party Name", margin + 12f, yPos + 16f, p)
            
            p.textAlign = Paint.Align.RIGHT
            c.drawText("Sales & Exp", margin + 280f, yPos + 16f, p)
            c.drawText("Payments", margin + 380f, yPos + 16f, p)
            c.drawText("Net Balance", pw - margin - 12f, yPos + 16f, p)

            yPos += 30f
            p.isFakeBoldText = false
        }

        var c = newPage()

        drawTableHeader(c)

        if (parties.isEmpty()) {
            yPos += 20f
            p.textAlign = Paint.Align.CENTER; p.color = LIGHT_GRAY; p.textSize = 12f
            c.drawText("No parties registered.", pw / 2f, yPos, p)
        } else {
            for ((idx, party) in parties.withIndex()) {
                if (yPos > ph - 80f) {
                    c = newPage()
                    drawTableHeader(c)
                }

                val partyTx = transactions.filter { it.partyId == party.id || it.partyName == party.name }
                val totalIn = partyTx.filter { it.type == "Money In" }.sumOf { it.amount }
                val totalOut = partyTx.filter { it.type == "Money Out" }.sumOf { it.amount }
                val netBalance = totalIn - totalOut

                val isClient = party.partyType == "Client" || party.partyType == "Investor"
                val payments = if (isClient) totalIn else totalOut
                val salesExpenses = if (isClient) totalOut else totalIn

                if (idx % 2 == 0) {
                    p.color = Color.argb(15, 0, 0, 0)
                    c.drawRect(margin, yPos - 4f, pw - margin, yPos + 22f, p)
                }

                p.color = NAVY; p.textSize = 10f; p.textAlign = Paint.Align.LEFT; p.isFakeBoldText = true
                c.drawText(truncateText(party.name, 120f, p), margin + 12f, yPos + 12f, p)
                p.isFakeBoldText = false

                p.textAlign = Paint.Align.RIGHT; p.color = SLATE
                val salesText = if (salesExpenses > 0) indFmt.format(salesExpenses) else "0.00"
                c.drawText(salesText, margin + 280f, yPos + 12f, p)

                val paymentsText = if (payments > 0) indFmt.format(payments) else "0.00"
                c.drawText(paymentsText, margin + 380f, yPos + 12f, p)

                val balColor = if (netBalance >= 0) GREEN_DARK else RED_DARK
                val balText = indFmt.format(kotlin.math.abs(netBalance)) + " " + if (netBalance >= 0) "Paid" else "Received"
                p.color = balColor; p.isFakeBoldText = true
                c.drawText(balText, pw - margin - 12f, yPos + 12f, p)
                p.isFakeBoldText = false

                p.color = Color.parseColor("#E2E8F0"); p.strokeWidth = 0.5f
                c.drawLine(margin, yPos + 20f, pw - margin, yPos + 20f, p)

                yPos += 24f
            }
        }

        val fc = canvas!!
        p.color = BORDER; p.strokeWidth = 1f
        fc.drawLine(margin, ph - 65f, pw - margin, ph - 65f, p)
        p.color = LIGHT_GRAY; p.textSize = 9f; p.isFakeBoldText = false; p.textAlign = Paint.Align.CENTER
        fc.drawText("Generated by ConstructPro  ·  ${timestampFormat.format(Date())}", pw / 2f, ph - 45f, p)
        fc.drawText("This is a computer-generated document and does not require a physical signature.", pw / 2f, ph - 30f, p)

        doc.finishPage(page!!)
        FileOutputStream(file).use { doc.writeTo(it) }; doc.close()
        return file
    }

    // ═══════════════════════════════════════════════════════════
    //  4. PAYMENT REPORT SUMMARY PDF (A4 — 595 × 842)
    // ═══════════════════════════════════════════════════════════
    fun generatePaymentSummaryReportPdfFile(
        context: Context,
        projectName: String,
        siteAddress: String,
        generatedBy: String,
        transactions: List<Transaction>,
        parties: List<com.example.data.Worker>,
        dateRange: String = "All Time"
    ): File {
        val fileName = "PaymentSummaryReport_${System.currentTimeMillis()}.pdf"
        val file = File(context.cacheDir, fileName)
        val doc = PdfDocument()

        val pw = 595; val ph = 842
        var pageNum = 0
        val margin = 40f
        val p = Paint().apply { isAntiAlias = true }

        val indFmt = NumberFormat.getNumberInstance(Locale.US).apply {
            maximumFractionDigits = 2; minimumFractionDigits = 2
        }

        var page: PdfDocument.Page? = null
        var canvas: Canvas? = null
        var yPos = 0f

        fun newPage(): Canvas {
            page?.let { doc.finishPage(it) }
            pageNum++
            val pi = PdfDocument.PageInfo.Builder(pw, ph, pageNum).create()
            page = doc.startPage(pi)
            canvas = page!!.canvas
            val c = canvas!!

            p.color = BG_PAGE; c.drawRect(0f, 0f, pw.toFloat(), ph.toFloat(), p)

            yPos = drawCommonHeader(
                c = c,
                p = p,
                pw = pw,
                margin = margin,
                reportTitle = "Payment Report",
                generatedBy = generatedBy,
                dateRange = dateRange,
                projectName = projectName,
                siteAddress = siteAddress,
                yStart = 40f
            )
            return c
        }

        var c = newPage()

        yPos += 10f
        p.textAlign = Paint.Align.LEFT
        p.color = NAVY; p.textSize = 12f; p.isFakeBoldText = true
        c.drawText("Summary", margin, yPos, p)
        yPos += 14f

        fun drawSummaryTable(
            title: String,
            headers: List<String>,
            rows: List<List<String>>,
            totals: List<String>
        ) {
            if (yPos > ph - 150f) { c = newPage() }
            
            p.textAlign = Paint.Align.LEFT
            p.color = NAVY; p.textSize = 11f; p.isFakeBoldText = true
            c.drawText(title, margin, yPos, p)
            yPos += 12f

            p.color = DARK_SLATE
            c.drawRoundRect(margin, yPos, pw - margin, yPos + 24f, 4f, 4f, p)
            p.color = Color.WHITE; p.textSize = 10f; p.isFakeBoldText = true
            
            c.drawText(headers[0], margin + 12f, yPos + 16f, p)
            p.textAlign = Paint.Align.RIGHT
            c.drawText(headers[1], margin + 220f, yPos + 16f, p)
            c.drawText(headers[2], margin + 360f, yPos + 16f, p)
            c.drawText(headers[3], pw - margin - 12f, yPos + 16f, p)

            yPos += 30f

            for ((idx, r) in rows.withIndex()) {
                if (yPos > ph - 80f) {
                    c = newPage()
                    p.color = DARK_SLATE
                    c.drawRoundRect(margin, yPos, pw - margin, yPos + 24f, 4f, 4f, p)
                    p.color = Color.WHITE; p.textSize = 10f; p.isFakeBoldText = true
                    p.textAlign = Paint.Align.LEFT
                    c.drawText(headers[0], margin + 12f, yPos + 16f, p)
                    p.textAlign = Paint.Align.RIGHT
                    c.drawText(headers[1], margin + 220f, yPos + 16f, p)
                    c.drawText(headers[2], margin + 360f, yPos + 16f, p)
                    c.drawText(headers[3], pw - margin - 12f, yPos + 16f, p)
                    yPos += 30f
                }

                if (idx % 2 == 0) {
                    p.color = Color.argb(15, 0, 0, 0)
                    c.drawRect(margin, yPos - 4f, pw - margin, yPos + 20f, p)
                }

                p.color = NAVY; p.textSize = 9f; p.isFakeBoldText = false; p.textAlign = Paint.Align.LEFT
                c.drawText(truncateText(r[0], 140f, p), margin + 12f, yPos + 12f, p)

                p.textAlign = Paint.Align.RIGHT
                c.drawText(r[1], margin + 220f, yPos + 12f, p)
                
                p.color = GREEN_DARK
                c.drawText(r[2], margin + 360f, yPos + 12f, p)
                
                p.color = RED_DARK
                c.drawText(r[3], pw - margin - 12f, yPos + 12f, p)

                p.color = Color.parseColor("#E2E8F0"); p.strokeWidth = 0.5f
                c.drawLine(margin, yPos + 22f, pw - margin, yPos + 22f, p)

                yPos += 26f
            }

            p.color = DARK_SLATE
            c.drawRect(margin, yPos - 4f, pw - margin, yPos + 20f, p)
            p.color = Color.WHITE; p.textSize = 10f; p.isFakeBoldText = true; p.textAlign = Paint.Align.LEFT
            c.drawText(totals[0], margin + 12f, yPos + 12f, p)

            p.textAlign = Paint.Align.RIGHT
            c.drawText(totals[1], margin + 220f, yPos + 12f, p)
            c.drawText(totals[2], margin + 360f, yPos + 12f, p)
            c.drawText(totals[3], pw - margin - 12f, yPos + 12f, p)
            p.isFakeBoldText = false

            yPos += 36f
        }

        // ── 1. TRADE SUMMARY ──
        val tradeGroups = transactions.groupBy { tx ->
            val w = parties.find { it.id == tx.partyId || it.name == tx.partyName }
            w?.partyType ?: "-"
        }
        val tradeRows = tradeGroups.map { (trade, txs) ->
            val entries = txs.size.toString()
            val totalIn = txs.filter { it.type == "Money In" }.sumOf { it.amount }
            val totalOut = txs.filter { it.type == "Money Out" }.sumOf { it.amount }
            listOf(
                trade,
                entries,
                if (totalIn > 0) indFmt.format(totalIn) else "0.00",
                if (totalOut > 0) indFmt.format(totalOut) else "0.00"
            )
        }
        val totalTradeEntries = transactions.size.toString()
        val totalTradeIn = transactions.filter { it.type == "Money In" }.sumOf { it.amount }
        val totalTradeOut = transactions.filter { it.type == "Money Out" }.sumOf { it.amount }
        val tradeTotals = listOf(
            "Total",
            totalTradeEntries,
            indFmt.format(totalTradeIn),
            indFmt.format(totalTradeOut)
        )

        drawSummaryTable("Trade Summary", listOf("Trade", "#Entries", "Received", "Paid"), tradeRows, tradeTotals)

        // ── 2. CATEGORY SUMMARY ──
        val catGroups = transactions.groupBy { it.category }
        val catRows = catGroups.map { (cat, txs) ->
            val entries = txs.size.toString()
            val totalIn = txs.filter { it.type == "Money In" }.sumOf { it.amount }
            val totalOut = txs.filter { it.type == "Money Out" }.sumOf { it.amount }
            listOf(
                cat,
                entries,
                if (totalIn > 0) indFmt.format(totalIn) else "0.00",
                if (totalOut > 0) indFmt.format(totalOut) else "0.00"
            )
        }
        val catTotals = listOf(
            "Total",
            totalTradeEntries,
            indFmt.format(totalTradeIn),
            indFmt.format(totalTradeOut)
        )

        drawSummaryTable("Category Summary", listOf("Category", "#Entries", "Received", "Paid"), catRows, catTotals)

        val fc = canvas!!
        p.color = BORDER; p.strokeWidth = 1f
        fc.drawLine(margin, ph - 65f, pw - margin, ph - 65f, p)
        p.color = LIGHT_GRAY; p.textSize = 9f; p.isFakeBoldText = false; p.textAlign = Paint.Align.CENTER
        fc.drawText("Generated by ConstructPro  ·  ${timestampFormat.format(Date())}", pw / 2f, ph - 45f, p)
        fc.drawText("This is a computer-generated document and does not require a physical signature.", pw / 2f, ph - 30f, p)

        doc.finishPage(page!!)
        FileOutputStream(file).use { doc.writeTo(it) }; doc.close()
        return file
    }

    fun generatePaymentTransactionsReportPdfFile(
        context: Context,
        projectName: String,
        siteAddress: String,
        generatedBy: String,
        transactions: List<Transaction>,
        dateRange: String = "All Time"
    ): File {
        val fileName = "PaymentTransactionsReport_${System.currentTimeMillis()}.pdf"
        val file = File(context.cacheDir, fileName)
        val doc = PdfDocument()

        val pw = 595; val ph = 842
        var pageNum = 0
        val margin = 30f
        val p = Paint().apply { isAntiAlias = true }

        val indFmt = NumberFormat.getNumberInstance(Locale.US).apply {
            maximumFractionDigits = 2; minimumFractionDigits = 2
        }

        var page: PdfDocument.Page? = null
        var canvas: Canvas? = null
        var yPos = 0f

        fun newPage(): Canvas {
            page?.let { doc.finishPage(it) }
            pageNum++
            val pi = PdfDocument.PageInfo.Builder(pw, ph, pageNum).create()
            page = doc.startPage(pi)
            canvas = page!!.canvas
            val c = canvas!!

            p.color = BG_PAGE; c.drawRect(0f, 0f, pw.toFloat(), ph.toFloat(), p)

            yPos = drawCommonHeader(
                c = c,
                p = p,
                pw = pw,
                margin = margin,
                reportTitle = "Payment Report",
                generatedBy = generatedBy,
                dateRange = dateRange,
                projectName = projectName,
                siteAddress = siteAddress,
                yStart = 40f
            )
            return c
        }

        fun drawTableHeader(c: Canvas) {
            p.color = DARK_SLATE
            c.drawRoundRect(margin, yPos, pw - margin, yPos + 24f, 4f, 4f, p)

            p.color = Color.WHITE; p.textSize = 9f; p.isFakeBoldText = true
            p.textAlign = Paint.Align.LEFT
            c.drawText("Date", margin + 8f, yPos + 16f, p)
            c.drawText("Party Name", margin + 80f, yPos + 16f, p)
            c.drawText("Type", margin + 185f, yPos + 16f, p)
            c.drawText("Description", margin + 375f, yPos + 16f, p)
            
            p.textAlign = Paint.Align.RIGHT
            c.drawText("Amount", margin + 360f, yPos + 16f, p)

            yPos += 30f
            p.isFakeBoldText = false
        }

        var c = newPage()

        val totalIn = transactions.filter { it.type == "Money In" }.sumOf { it.amount }
        val totalOut = transactions.filter { it.type == "Money Out" }.sumOf { it.amount }
        val totalBalance = totalIn - totalOut

        p.color = GREEN_DARK; p.textSize = 10f; p.isFakeBoldText = true
        c.drawText("Total Received: ${indFmt.format(totalIn)}", margin, yPos, p)
        p.color = RED_DARK
        c.drawText("Total Paid: ${indFmt.format(totalOut)}", margin + 180f, yPos, p)
        p.color = NAVY
        c.drawText("Balance: ${indFmt.format(totalBalance)}", margin + 360f, yPos, p)
        yPos += 20f

        drawTableHeader(c)

        val sortedTxs = transactions.sortedBy { it.date }

        for ((idx, tx) in sortedTxs.withIndex()) {
            if (yPos > ph - 80f) {
                c = newPage()
                drawTableHeader(c)
            }

            val isIn = tx.type == "Money In"

            if (idx % 2 == 0) {
                p.color = Color.argb(15, 0, 0, 0)
                c.drawRect(margin, yPos - 4f, pw - margin, yPos + 22f, p)
            }

            p.color = NAVY; p.textSize = 9f; p.textAlign = Paint.Align.LEFT
            c.drawText(tx.date, margin + 8f, yPos + 12f, p)
            
            val partyName = tx.partyName ?: "-"
            c.drawText(truncateText(partyName, 90f, p), margin + 80f, yPos + 12f, p)

            val typeColor = if (isIn) GREEN_DARK else RED_DARK
            val typeText = if (isIn) "Received" else "Paid"
            p.color = typeColor
            c.drawText(typeText, margin + 185f, yPos + 12f, p)

            p.color = SLATE
            val desc = tx.description.ifEmpty { "-" }
            c.drawText(truncateText(desc, 165f, p), margin + 375f, yPos + 12f, p)

            p.textAlign = Paint.Align.RIGHT
            p.isFakeBoldText = true
            p.color = typeColor
            val amtText = (if (isIn) "+" else "-") + indFmt.format(tx.amount)
            c.drawText(amtText, margin + 360f, yPos + 12f, p)
            p.isFakeBoldText = false

            p.color = Color.parseColor("#E2E8F0"); p.strokeWidth = 0.5f
            c.drawLine(margin, yPos + 20f, pw - margin, yPos + 20f, p)

            yPos += 24f
        }

        val fc = canvas!!
        p.color = BORDER; p.strokeWidth = 1f
        fc.drawLine(margin, ph - 65f, pw - margin, ph - 65f, p)
        p.color = LIGHT_GRAY; p.textSize = 9f; p.isFakeBoldText = false; p.textAlign = Paint.Align.CENTER
        fc.drawText("Generated by ConstructPro  ·  ${timestampFormat.format(Date())}", pw / 2f, ph - 45f, p)
        fc.drawText("This is a computer-generated document and does not require a physical signature.", pw / 2f, ph - 30f, p)

        doc.finishPage(page!!)
        FileOutputStream(file).use { doc.writeTo(it) }; doc.close()
        return file
    }

    fun generatePartyTransactionsReportPdfFile(
        context: Context,
        projectName: String,
        siteAddress: String,
        generatedBy: String,
        party: com.example.data.Worker,
        transactions: List<Transaction>,
        dateRange: String = "All Time"
    ): File {
        val fileName = "PartyTransactions_${party.name.replace(" ", "_")}_${System.currentTimeMillis()}.pdf"
        val file = File(context.cacheDir, fileName)
        val doc = PdfDocument()

        val pw = 595; val ph = 842
        var pageNum = 0
        val margin = 30f
        val p = Paint().apply { isAntiAlias = true }

        val indFmt = NumberFormat.getNumberInstance(Locale.US).apply {
            maximumFractionDigits = 2; minimumFractionDigits = 2
        }

        var page: PdfDocument.Page? = null
        var canvas: Canvas? = null
        var yPos = 0f

        fun newPage(): Canvas {
            page?.let { doc.finishPage(it) }
            pageNum++
            val pi = PdfDocument.PageInfo.Builder(pw, ph, pageNum).create()
            page = doc.startPage(pi)
            canvas = page!!.canvas
            val c = canvas!!

            p.color = BG_PAGE; c.drawRect(0f, 0f, pw.toFloat(), ph.toFloat(), p)

            yPos = drawCommonHeader(
                c = c,
                p = p,
                pw = pw,
                margin = margin,
                reportTitle = "Party Transactions",
                generatedBy = generatedBy,
                dateRange = dateRange,
                projectName = projectName,
                siteAddress = siteAddress,
                yStart = 35f
            )

            p.color = Color.parseColor("#475569")
            p.textSize = 9f
            p.isFakeBoldText = false
            p.textAlign = Paint.Align.LEFT
            c.drawText("Party Name: ${party.name} (${party.partyType})", margin, yPos, p)
            yPos += 16f

            return c
        }

        fun drawTableHeader(c: Canvas) {
            p.color = Color.parseColor("#1E293B")
            c.drawRoundRect(margin, yPos, pw - margin, yPos + 24f, 4f, 4f, p)

            p.color = Color.WHITE; p.textSize = 9f; p.isFakeBoldText = true
            p.textAlign = Paint.Align.LEFT
            c.drawText("Date", margin + 8f, yPos + 16f, p)
            c.drawText("Type", margin + 80f, yPos + 16f, p)
            c.drawText("Description", margin + 335f, yPos + 16f, p)
            
            p.textAlign = Paint.Align.RIGHT
            c.drawText("Amount", margin + 220f, yPos + 16f, p)
            c.drawText("Balance", margin + 320f, yPos + 16f, p)

            yPos += 30f
            p.isFakeBoldText = false
        }

        var c = newPage()

        val partyTxs = transactions.filter { it.partyId == party.id || it.partyName == party.name }
        val sortedTxs = partyTxs.sortedBy { it.date }

        val totalIn = sortedTxs.filter { it.type == "Money In" }.sumOf { it.amount }
        val totalOut = sortedTxs.filter { it.type == "Money Out" }.sumOf { it.amount }
        val totalBalance = totalIn - totalOut

        p.color = GREEN_DARK; p.textSize = 10f; p.isFakeBoldText = true
        c.drawText("Total Received: ${indFmt.format(totalIn)}", margin, yPos, p)
        p.color = RED_DARK
        c.drawText("Total Paid: ${indFmt.format(totalOut)}", margin + 180f, yPos, p)
        p.color = NAVY
        c.drawText("Balance: ${indFmt.format(totalBalance)}", margin + 360f, yPos, p)
        yPos += 20f

        drawTableHeader(c)

        var runningBalance = 0.0

        for ((idx, tx) in sortedTxs.withIndex()) {
            if (yPos > ph - 80f) {
                c = newPage()
                drawTableHeader(c)
            }

            val isIn = tx.type == "Money In"
            runningBalance += if (isIn) tx.amount else -tx.amount

            if (idx % 2 == 0) {
                p.color = Color.argb(15, 0, 0, 0)
                c.drawRect(margin, yPos - 4f, pw - margin, yPos + 22f, p)
            }

            p.color = NAVY; p.textSize = 9f; p.textAlign = Paint.Align.LEFT
            c.drawText(tx.date, margin + 8f, yPos + 12f, p)
            
            val typeColor = if (isIn) GREEN_DARK else RED_DARK
            val typeText = if (isIn) "Received" else "Paid"
            p.color = typeColor
            c.drawText(typeText, margin + 80f, yPos + 12f, p)

            p.color = SLATE
            val desc = tx.description.ifEmpty { "-" }
            c.drawText(truncateText(desc, 165f, p), margin + 335f, yPos + 12f, p)

            p.textAlign = Paint.Align.RIGHT
            p.isFakeBoldText = true
            p.color = typeColor
            val amtText = (if (isIn) "+" else "-") + indFmt.format(tx.amount)
            c.drawText(amtText, margin + 220f, yPos + 12f, p)

            p.color = NAVY
            c.drawText(indFmt.format(runningBalance), margin + 320f, yPos + 12f, p)
            p.isFakeBoldText = false

            p.color = Color.parseColor("#E2E8F0"); p.strokeWidth = 0.5f
            c.drawLine(margin, yPos + 20f, pw - margin, yPos + 20f, p)

            yPos += 24f
        }

        val fc = canvas!!
        p.color = BORDER; p.strokeWidth = 1f
        fc.drawLine(margin, ph - 65f, pw - margin, ph - 65f, p)
        p.color = LIGHT_GRAY; p.textSize = 9f; p.isFakeBoldText = false; p.textAlign = Paint.Align.CENTER
        fc.drawText("Generated by ConstructPro  ·  ${timestampFormat.format(Date())}", pw / 2f, ph - 45f, p)
        fc.drawText("This is a computer-generated document and does not require a physical signature.", pw / 2f, ph - 30f, p)

        doc.finishPage(page!!)
        FileOutputStream(file).use { doc.writeTo(it) }; doc.close()
        return file
    }

    // ═══════════════════════════════════════════════════════════
    //  SHARE
    // ═══════════════════════════════════════════════════════════
    fun sharePdfFile(context: Context, file: File, title: String = "Share PDF") {
        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.fileprovider",
            file
        )
        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }
        context.startActivity(Intent.createChooser(intent, title))
    }
}
